### ISSUE TITLE
Screenshots should link to actual images

### ISSUE THREAD

**Issue by Uhkis** [zaszi/dotfiles#1]
Screenshots are currently linked to GitHub pages instead of the actual images, this causes horizontal scrollbar on some images. 

For example https://github.com/zaszi/dotfiles/blob/master/images/qutebrowser.png opens to HTML page with a scrollbar instead of the actual image file https://raw.githubusercontent.com/zaszi/dotfiles/master/images/qutebrowser.png

**Comment by zaszi** [comment]
Thanks for the find! Fixed in 9871ecde0338b2d687e977422969e71a3e9db9c8.
